### ISSUE TITLE
Make facets mobile-friendly

### ISSUE THREAD

**Issue by derekenos** [CollectionBuilder/collectionbuilder-sa_draft#15]

**Comment by evanwill** [comment]
I think this is interconnected with #16 , something like:

```
<div class="row">
  <div class="col-md-4"> facets </div>
  <div class="col-md-8"> results </div>
</div>
```

so on mobile the facets are on top--but would be hidden probably, with a button to open the facet pane?

**Comment by derekenos** [comment]
Basic implementation here: https://github.com/CollectionBuilder/collectionbuilder-sa_draft/pull/73
