### ISSUE TITLE
not all collections have digital collection field

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-sa_draft#24]
https://github.com/CollectionBuilder/collectionbuilder-sa_draft/blob/0dc973a07b9ad13268cd20b7f80acfe1d2be217d/Rakefile#L237

@derekenos Replace line with this?

index_name = $collection_name_to_index_name.call(config[:elasticsearch_index])

seems to work in my test ...

**Comment by evanwill** [comment]
i used @dcnb fix too, which seems to make sense.
what is the implications of the `_index` value for the search? 
Do we always search just one at a time, or is there some reason to have a field like "digital_collection" that gives the option to group the items into separate indexes?

**Comment by derekenos** [comment]
@dcnb, I didn't realize that about `digital_collection` and `collection_name_to_index_name()` predates `elasticsearch-index` in the config.

We can delete the `collection_name_to_index_name()` function altogether and simply use:
```
index_name = config[:elasticsearch_index]
```

I'll plan to address these issues in code after next week.

**Comment by derekenos** [comment]
Fixed: https://github.com/CollectionBuilder/collectionbuilder-sa_draft/commit/58f9bbbfa3ae4489c1638a10f81e27e7422a49f1
