### ISSUE TITLE
collection id / short name for ES index and multicollection search

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-sa_draft#29]
- add value to _config.yml. @derekenos is this different than current `elasticsearch-index` value?
- treat as immutable after set up 

is there a way to send ES information about the collection (`title`, url, etc) so that it knows for display on the centralized search? (like is there an index of collections that we contribute collection info to, vs. the individual object indexes. index of collections might be useful for a collection search if we want to provide more info about the collection itself overall.)

**Comment by derekenos** [comment]
Addressed by this PR: https://github.com/CollectionBuilder/collectionbuilder-sa_draft/pull/48
