### ISSUE TITLE
Files created within the container are owned by root user on local filesystem

### ISSUE THREAD

**Issue by derekenos** [CollectionBuilder/collectionbuilder-sa_draft#5]
This is a know issue and can be address in a couple of different ways:

1. Do a "sudo chown --recursive $USER:$USER ./*` on your local machine to reassign ownership to your normal user

2. **[the good option]** Create a user within the docker container with the same id as your host machine's user.

Here's an example from one of my Dockerfile's:

```
ARG user_name
ARG user_uid

RUN apt update && \
    apt upgrade -y

WORKDIR /app

RUN useradd --uid $user_uid --groups root $user_name
USER $user_name
```
While `user_name` is readily available from the environment as `$USER`, `user_id` is a little tricky to get at, but I got a guy.

**Comment by evanwill** [comment]
This comes up when you generate new image derivatives they have wrong owner? Or html output from Jekyll as well?
Do you if Windows pays attention to the owner or is this applicable only to linux/mac?

**Comment by derekenos** [comment]
This applies to all files created within the container, including the Jekyll HTML output.
That's good question about Windows. I'll have to set it up and test it out.

**Comment by derekenos** [comment]
The current `Dockerfile` creates a non-root default user: https://github.com/CollectionBuilder/collectionbuilder-sa_draft/blob/docker/Dockerfile#L8-L13
