### ISSUE TITLE
Bundle up multiple operations into a single rake task

### ISSUE THREAD

**Issue by derekenos** [CollectionBuilder/collectionbuilder-sa_draft#53]
Though instructive, it's tedious to have to execute each rake task individually. Where possible, we should bundle up multiple operations into a single task.

**Comment by evanwill** [comment]
yeah! Maybe still surface the individual tasks, but have a do-it-all task if you know what is going on and everything is set up nice.

**Comment by evanwill** [comment]
@derekenos the Rakefile is all one huge file at this point-- does it make sense to break it up in to components to make it easier to keep track of?

**Comment by derekenos** [comment]
@evanwill, definitely. I'll plan on splitting that Rakefile up into reasonable chunks.

**Comment by derekenos** [comment]
Done: https://github.com/CollectionBuilder/collectionbuilder-sa_draft/pull/66
