### ISSUE TITLE
extracting text from PDF

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-sa_draft#6]
@derekenos in the past I have been using `pdftotext` from the `poppler-utils` package (or comes via [Xpdf tools](https://www.xpdfreader.com/download.html) for non-linux):
`pdftotext filename.pdf outputname.txt`

Use case: 
extract ocr or borndigital text from PDF to be indexed in full-text search. 

Potential issues: 
- PDFs not OCRed
- badly formed PDFs 
- giant PDFs
- horrific OCR quality = junk text

I think we can assume quality of the original pdfs and their ocr is out of scope for this project. 
I think we will need to think about how big the full-text search gets with a large document collection.

**Comment by derekenos** [comment]
`pdftotext` is now being used by the `extract_pdf_text` rake task: https://github.com/CollectionBuilder/collectionbuilder-sa_draft/blob/master/Rakefile#L189
